"""add_high_water_mark_to_positions

Revision ID: 9632ae77fe88
Revises: cb3996e50464
Create Date: 2026-03-30 09:30:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9632ae77fe88'
down_revision: str | Sequence[str] | None = 'cb3996e50464'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add high_water_mark column to positions table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('high_water_mark', sa.DECIMAL(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove high_water_mark column from positions table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'high_water_mark')
    # ### end Alembic commands ###