"""initial_schema

Revision ID: cb3996e50464
Revises:
Create Date: 2026-03-26 14:08:13.304684

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb3996e50464'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types safely
    op.execute("DO $$ BEGIN "
               "CREATE TYPE market_enum AS ENUM ('KR', 'US'); "
               "EXCEPTION WHEN duplicate_object THEN null; "
               "END $$;")
    
    op.execute("DO $$ BEGIN "
               "CREATE TYPE decision_action_enum AS ENUM ('BUY', 'SELL', 'HOLD'); "
               "EXCEPTION WHEN duplicate_object THEN null; "
               "END $$;")
    
    op.execute("DO $$ BEGIN "
               "CREATE TYPE position_status_enum AS ENUM ('OPEN', 'CLOSED'); "
               "EXCEPTION WHEN duplicate_object THEN null; "
               "END $$;")
    
    op.execute("DO $$ BEGIN "
               "CREATE TYPE action_enum AS ENUM ('HOLD', 'BUY', 'PARTIAL_SELL', 'FULL_EXIT'); "
               "EXCEPTION WHEN duplicate_object THEN null; "
               "END $$;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'analysis_log',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('market', sa.Text(), nullable=False),
        sa.Column('executed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column(
            'ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_log')),
    )
    op.create_index(
        op.f('ix_analysis_log_date'), 'analysis_log', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_analysis_log_executed'), 'analysis_log', ['executed'], unique=False
    )
    op.create_table(
        'market_data',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column('market', sa.Text(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('high', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('low', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('close', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('volume', sa.BigInteger(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data')),
        sa.UniqueConstraint(
            'ticker', 'market', 'date', name='uq_market_data_ticker_market_date'
        ),
    )
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(
        op.f('ix_market_data_ticker'), 'market_data', ['ticker'], unique=False
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('api_key_encrypted', sa.Text(), nullable=True),
        sa.Column(
            'preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table(
        'decision_log',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column(
            'action',
            sa.Text(),
            nullable=False,
        ),
        sa.Column('price', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('quantity', sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column('ai_suggested', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_decision_log_user_id_users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_log')),
    )
    op.create_index(
        op.f('ix_decision_log_ai_suggested'),
        'decision_log',
        ['ai_suggested'],
        unique=False,
    )
    op.create_index(
        op.f('ix_decision_log_ticker'), 'decision_log', ['ticker'], unique=False
    )
    op.create_index(
        op.f('ix_decision_log_user_id'), 'decision_log', ['user_id'], unique=False
    )
    op.create_table(
        'positions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column('market', sa.Text(), nullable=False),
        sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('avg_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column(
            'status',
            sa.Text(),
            nullable=False,
            server_default='OPEN',
        ),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_positions_user_id_users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    )
    op.create_index(op.f('ix_positions_ticker'), 'positions', ['ticker'], unique=False)
    op.create_index(
        op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False
    )
    op.create_table(
        'strategy_output',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('analysis_log_id', sa.UUID(), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column(
            'action',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'take_profit_levels',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            'stop_loss_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('rationale', sa.String(length=100), nullable=False),
        sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['analysis_log_id'],
            ['analysis_log.id'],
            name=op.f('fk_strategy_output_analysis_log_id_analysis_log'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_output')),
    )
    op.create_index(
        op.f('ix_strategy_output_analysis_log_id'),
        'strategy_output',
        ['analysis_log_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_strategy_output_ticker'), 'strategy_output', ['ticker'], unique=False
    )
    
    # Add enum constraints after table creation
    op.execute("ALTER TABLE analysis_log ALTER COLUMN market TYPE market_enum USING market::market_enum")
    op.execute("ALTER TABLE market_data ALTER COLUMN market TYPE market_enum USING market::market_enum") 
    op.execute("ALTER TABLE decision_log ALTER COLUMN action TYPE decision_action_enum USING action::decision_action_enum")
    op.execute("ALTER TABLE positions ALTER COLUMN market TYPE market_enum USING market::market_enum")
    
    # Handle positions.status with default value
    op.execute("ALTER TABLE positions ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE positions ALTER COLUMN status TYPE position_status_enum USING status::position_status_enum")
    op.execute("ALTER TABLE positions ALTER COLUMN status SET DEFAULT 'OPEN'")
    
    op.execute("ALTER TABLE strategy_output ALTER COLUMN action TYPE action_enum USING action::action_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_output_ticker'), table_name='strategy_output')
    op.drop_index(
        op.f('ix_strategy_output_analysis_log_id'), table_name='strategy_output'
    )
    op.drop_table('strategy_output')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_ticker'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_decision_log_user_id'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_ticker'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_ai_suggested'), table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_data_ticker'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_analysis_log_executed'), table_name='analysis_log')
    op.drop_index(op.f('ix_analysis_log_date'), table_name='analysis_log')
    op.drop_table('analysis_log')
    
    # Drop enum types safely
    op.execute("DROP TYPE IF EXISTS action_enum")
    op.execute("DROP TYPE IF EXISTS position_status_enum")
    op.execute("DROP TYPE IF EXISTS decision_action_enum")
    op.execute("DROP TYPE IF EXISTS market_enum")
    # ### end Alembic commands ###
